#!/usr/bin/env python3

import rospy
from naoqi_bridge_msgs.msg import JointAnglesWithSpeed

def move_right_arm():
    rospy.init_node('move_right_arm_node', anonymous=True)
    pub = rospy.Publisher('/joint_angles', JointAnglesWithSpeed, queue_size=10)
    rospy.sleep(1)  # Ensure the publisher is set up

    msg = JointAnglesWithSpeed()
    msg.joint_names = ['RShoulderPitch', 'RShoulderRoll', 'RElbowYaw', 'RElbowRoll', 'RWristYaw']
    msg.joint_angles = [-0.5, -0.3, 1.5, 1.0, -0.5]
    msg.speed = 0.1
    msg.relative = False  # Absolute movement

    pub.publish(msg)
    rospy.loginfo("Right arm moved to lifted position")

if __name__ == '__main__':
    move_right_arm()
